### ISSUE TITLE
Prune / Refine Responsive breakpoints

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#106]
The current t-shirt-sizes collection of breakpoints is probably too much. 

- [x] Whittle them down the bare minimum.
- [x] Carefully adjust all current uses, both in `fsa-style` and `fsa-design-system`
- [x] Reconcile with USWDS breakpoints (`$small-screen`, `$medium-screen`, `$large-screen`)

Generally thinking...

* XS
* S
* ~~SM~~
* M
* ~~MML~~
* ~~ML~~
* ~~MLL~~
* L
* XL
* XXL (maybe not?)

Initially **blocks** https://github.com/USDA-FSA/fsa-design-system/issues/16

**Comment by brianmillsUX** [comment]
As it's clear and not overwhelming, agree on 5-point scale of XS > S > M > L > XL - good call.
