### ISSUE TITLE
Major bump to fsa-style version

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#146]
I currently have `fsa-style` (the actual downloadable/installable assets) at `0.2.9` with current branched work targeting `0.2.10`. However, the previous "FSA Style Guide" (you know, the PDF from the last century) is versioned as `1.2.4`. 

So this issue is to do a major bump to at least `2.0.0`, and reassign wip branches to it.

cc'ing @brianmillsUX, @jeremyhaas, no action required.

**Comment by brianmillsUX** [comment]
Funny story: this is how this project was initially proposed almost two years ago. :)

Using the 2.0 versioning is a seemingly simple detail that inherently reframes what came before as we continue to move ahead.

**Comment by francisrupert** [comment]
closed via https://github.com/USDA-FSA/fsa-style/commit/31afe20bdeb0f5387ae839ae642524f60f82392d
