### ISSUE TITLE
README

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#17]
### General outline

* Summary
* Contents
* Getting Started
* Building and Running Locally
* Contributing
* Reuse of open-source style guides

**Comment by francisrupert** [comment]
@brianmillsUX,

Can you review the README.md of this repo? Note this isn't the Design System specifically, but for the installable/downloadable HTML/CSS assets. 

While I know some of the tech language may not fully make sense to you, I want to make sure it flows well, is coherent, and so on.

Feel free to create a branch of this repo to suggest edits.

**Comment by brianmillsUX** [comment]
You bet! While I ended up taking a quick look at it last week, it requires a deeper review. Thank you!

**Comment by francisrupert** [comment]
@brianmillsUX,

### Updated Request

Rather than review this README.md, can you instead review the [Getting Started](http://usda-fsa.github.io/fsa-design-system/getting-started/) page? These two are effectively a mirror, so I'd rather you view it in that context.

### Action

* Any feedback or response should be **not** on this Issue (#17), but instead on https://github.com/USDA-FSA/fsa-design-system/issues/18. I've updated you as an assignee on that issue.
* If you want to make edits, do it on the same branch you've already been working with (Sync before doing so) and let me know on https://github.com/USDA-FSA/fsa-design-system/issues/18 that you've done so.
