### ISSUE TITLE
Content Tabs

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#175]
### Task

- [x] Design 
- [x] Build HTML/CSS
- [x] Namespace from `pcp` to `fsa`
- [x] Variations
- [x] Responsive

### Etc.

Port in from PCP, and adjust as needed.

![image](https://user-images.githubusercontent.com/1165933/29780553-d86c4a84-8bdb-11e7-8623-01c923233bd9.png)

### Details

There should be very little HTML/CSS adjustment to be made. Here's generally the steps to take:

1. Pull PCP's [`MASTER`](https://github.com/USDA-FSA/pcp/tree/master) branch.
1. Create a `feature/content-tabs` branch
1. Copy the HTML from `component_content-tabs.html`. 
1. Copy in the SASS, changing from `pcp-content-tabs` to `fsa-content-tabs`
1. Recommend any changes/adjustments/exclusions
1. Push `feature/content-tabs` branch
1. Post on this thread requesting review and any commentary/questions, mentioning me. If necessary, we'll peer review in person.
1. Once we've both reviewed and feel good about it, merge to `develop` branch

For each published release we'll collect everything on that `develop` branch before moving to `master` and publishing to either `2.0.5` or possibly `2.1.0`.

As a matter of habit reference this issue in commit messages, keeping them short but useful. Examples:

* "initial port from PCP of content-tabs component [amends #175]"
* "changed namespace of content tabs from 'pcp' to 'fsa' and added foo variation [amends #175]"

A good historical reference is to view the [commit history of `_pcp.content-tabs.scss`](https://github.com/USDA-FSA/pcp/commits/master/src/stylesheets/components/_pcp.content-tabs.scss), from bottom to top.

**Comment by francisrupert** [comment]
@bignamehere,

I've updated the [initial post of this Issue](https://github.com/USDA-FSA/fsa-style/issues/175#issue-253367373) with some further clarification. Respond to this thread with any questions/discussion/etc.

**Comment by francisrupert** [comment]
@bignamehere,

Just remembered, you'll see `class="HINT"` here and there throughout the PCP prototype. Remove those from HTML.

**Comment by bignamehere** [comment]
@francisrupert 

I have added feature/content-tabs branch and ready to review. One question I have is on the Large variation if we should have RWD lower the font size on small screens. Thoughts?

**Comment by francisrupert** [comment]
@bignamehere,

Yeah, in fact I'd make all variations the same font-size, at least until the `L` breakpoint, or maybe `M` breakpoint for some or one of them. Play with it.

**Comment by francisrupert** [comment]
@bignamehere,

I've made some adjustments and additions to this component.

1. Pull my branch `feature/content-tab-additions`
1. To get a handle on what I've done, `grunt` it and glance at this [branch's commit history](https://github.com/USDA-FSA/fsa-style/commits/feature/content-tabs-additions): specifically c988c11323d2699a08c1d8e95faed104ef9e0a87, 0c2870735c7f2a166a8c25a0656a8c072f59d697, 38a318d2852bd7f71e0491503632872bdaa21270
1. Merge my `feature/content-tabs-additions` to your `feature/content-tabs`.

Let me know when you've done the changes mentioned in your https://github.com/USDA-FSA/fsa-style/issues/175#issuecomment-330952110 and and my https://github.com/USDA-FSA/fsa-style/issues/175#issuecomment-330966902. 

Once we both approve, we'd merge `feature/content-tabs` to `develop`.

**Comment by bignamehere** [comment]
@francisrupert 

Pulled your content tabs code in and added code for responsive behavior [7826f94](https://github.com/USDA-FSA/fsa-style/commit/7826f946e3b8f6c57235df84443dfe9ab5dc233b). Need your opinion on small screen stacking. I would recommend future development of this component takes the small screen size and turns the tabs into an accordion like [this example](https://foundation.zurb.com/building-blocks/blocks/material-design-tabs.html). 

Pull down and let me know what you think.

**Comment by francisrupert** [comment]
Tested and confirmed responsive horizontal touch scrolling on devices.

**Comment by francisrupert** [comment]
@bignamehere,

Note I've merged my `feature/content-tabs--rwd` branch onto `develop`.
