### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#178]
### Task

- [x] Design 
- [x] Build HTML/CSS
- [x] Variations
- [x] Script demo of before/after states (plain vanilla, non-jQuery)

### Etc.

Port in from PCP, and adjust as needed.

![image](https://user-images.githubusercontent.com/1165933/29780664-30555a6a-8bdc-11e7-9b58-ab552b3cd12b.png)

**Comment by bignamehere** [comment]
@francisrupert  starting on this one now, let me know if it is not ready.

**Comment by francisrupert** [comment]
@bignamehere,

Yes of course. In fact I'd like to use this as a test case of us scripting the interaction with **vanilla js**, with no jQuery at all. I've already done so with [`fsa-nav-global.js`](https://github.com/USDA-FSA/fsa-style/blob/develop/src/js/components/fsa-nav-global.js), hopefully that'll give you an an idea.

So take a look at what I've scripted in PCP's `prototype.js` for `.pcp-modal`; backwards-engineer it, ask questions, and come up with a very simple and easy to follow script -- positing how you think developers that must create their equivalent would benefit from it.

**Comment by bignamehere** [comment]
@francisrupert 

Pull down feature/modal and take a look for a peer code review and to start a discussion on the JavaScript implementation.

**Comment by francisrupert** [comment]
Looks smooth and clean at first glance. Will take a deeper look today.

**Comment by francisrupert** [comment]
@bignamehere,

Let's be sure to include issue reference in commit messages. For retroactive tracking purposes, I'm associating the commit hashes below as a comment.

* 077de112066c54d3798b7d222f28cfb8dcca3d11: added stubbed JS code for modal [#178 initial]
* d6ca93c77377b51549055c689b5297d9fbeadca8: created JS only modal [amends #178]

**Comment by francisrupert** [comment]
Outstanding start. A few points I'll outline below and review in person for further clarification and/or discussion.

Now that I've looked at it, I should have included a primary requirement as it relates to PCP (and also applies to #177 and #179):

> Must be **retroactively compatible** with the PCP prototype, such that nothing about PCP should be updated - except of course for `pcp-` to `fsa-` namespace.

So a few things to realize that requirement and make this simpler:

1. Maintain `data-behavior` as the trigger and use `data-target` to pass the `id`.
    * Doing so will also remove the need to have the `new Modal()` in HTML at bottom of page.
    * Instead of using `class="fsa-modal-trigger"`, it'd be on click of `[data-behavior~="open-modal"]`, as seen on [prototype.js#L142](https://github.com/USDA-FSA/pcp/blob/master/src/js/prototype.js#L142).
    * Same for `data-behavior="close-modal"`, [prototype.js#L162](https://github.com/USDA-FSA/pcp/blob/master/src/js/prototype.js#L162)
    * Since the targeted modal's ID is passed from `data-target`'s value', there's no need to have it in the `new Modal()` at bottom of page.
1. Modal must be **focused** when opened (that's why the modal has `tabindex="0"`), and closing modal **returns** focus to the originating trigger. Think keyboard-only access. You can see that in play at...
    * [prototype.js#L155](https://github.com/USDA-FSA/pcp/blob/master/src/js/prototype.js#L155) (forgive my lazy use of `setTimeout()`)
    * [prototype.js#L173](https://github.com/USDA-FSA/pcp/blob/master/src/js/prototype.js#L173)
    * Note the role that `[data-modal-origin]` plays.
1. Scrap `closeOutside`.
1. `[aria-expanded="false"]`. I failed to do this for PCP, but we do need to toggle `[aria-expanded="false||true"]` on the trigger.
    * This does violate my note above about "not updating PCP html", but is negligible. 

So with the above updates, here's the HTML for the trigger...

```html
<button data-behavior="open-modal" data-target="UNIQUE-ID-GGFD36765SSSGH" aria-expanded="false" type="button">Default</button>
```
...and when modal is open...
```html
<button data-behavior="open-modal" data-target="UNIQUE-ID-GGFD36765SSSGH" aria-expanded="true" type="button">Default</button>
```
...and...
```javascript
  <script>
    var defaultModal = new Modal....
    ....
    ....
  </script>
```
... is removed.

**Comment by bignamehere** [comment]
@francisrupert 

updated code based on our discussions and pushed to remote branch [532a7b0](https://github.com/USDA-FSA/fsa-style/commit/532a7b06cb7613bd54052fd6379d9191ded05251)

should I merge into develop?

**Comment by francisrupert** [comment]
@bignamehere,

Awesome. I've updated `feature/modal` branch with a few changes/corrections. Pull that down and take a look alongside my commit messages (their effectively a "comment" in this comment thread immediately above this comment).

Beyond that, yep, go ahead and merge to `develop`.

**Comment by francisrupert** [comment]
@bignamehere,

Late-breaking addition request: **keyboard trap**.

If you think you can add this as part of this `feature/`, go for it. If you think we should do it some other time, then create new Issue for it - presumably to [Milestone: MVP+](https://github.com/USDA-FSA/fsa-style/milestone/11).

Inspiration examples:
* https://allyjs.io/tutorials/accessible-dialog.html#trapping-focus-inside-the-dialog
* http://usda-fsa.github.io/fsa-design-system/guides/accessibility/keyboard#keyboard-trap

**Comment by bignamehere** [comment]
@francisrupert 

Added tab trapping to the [latest feature update](https://github.com/USDA-FSA/fsa-style/tree/feature/modal)  

take a look and if we are good, I will merge into develop

**Comment by francisrupert** [comment]
Looks awesome, performs perfectly. Go ahead and merge to `dev` branch.

I noticed you've done a sort of private/public approach -- specifically the use of `_` character for private. I've not been that detailed a student of such js details, but it was immediately clear. 

My use of `$` for variables was to distinguish those that are actual DOM item(s) (e.g. `var $foo = $('.thing')`) vs something else (e.g. `var bar = "555"` or `var baz = true`).

**Comment by bignamehere** [comment]
@francisrupert  Yeah, I removed the $ references because I didn't want developers to see them and get confused as if they were jQuery. I don't might using them, but based on our conversation about jQuery, we might avoid them altogether, or have a quick chat as to when we want to use _ vs $ vs no prefix. I like the idea of using a _ more for properties or internally scoped objects within methods. Let's discuss when you get a chance.

**Comment by francisrupert** [comment]
@bignamehere,

I just remembered something I've been meaning to fix on the Modal.

### Bug

* [Screencast](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/screencasts/modal-scroll.webm)
* [Discovery:](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/LOB%20-%20Commodity%20Ops/PCP%20II%20Project/UX/Design/prototypes/master/workflow_discovery.html) 
  1. Click PNW's "Edit"
  1. Click Proteins
  1. Scroll willy nilly. 

### Solution

#### Fake JS to translate
```javascript
if (modal is open) {
  body.addClass('fsa-modal-is-open'); // or maybe html element
} else {
  body.removeClass('fsa-modal-is-open'); // or maybe html element
}
```

#### CSS

In `_fsa-modal.scss`:
```scss
.fsa-modal-is-open { overflow: hidden; }
```

**Comment by bignamehere** [comment]
@francisrupert 

I am not too sure what your intended fix would be above, but when I added the above, it prevented the double scrollbar, but then the content that was no on the screen was no longer accessible (viewable). If that is the desired effect, then let me know. 

I propose we have the content within the modal be scrollable if it does not fit on the screen or based on a breakpoint. I messed around with this solution and come up with what you see in the screenshot below. Let me know if this is the intended fix and your thoughts.

![modal-scrollbar](https://user-images.githubusercontent.com/2124049/31408418-1441b008-adce-11e7-88b1-93b5c561d467.jpg)

**Comment by bignamehere** [comment]
@francisrupert 

I added the scrollbar fix as seen in previous comment to the codebase. I think it works pretty well, but let me know your thoughts.

Diff: [fc45c23](https://github.com/USDA-FSA/fsa-style/commit/fc45c23d66c04487cce2d905c75d702c7f6e0492)

**Comment by bignamehere** [comment]
@francisrupert 

added new scrollbar fix. Should I merge into develop?

Diff: [7845bf9](https://github.com/USDA-FSA/fsa-style/commit/7845bf90aee94e7bf51956ea32260c8f92044234)

**Comment by francisrupert** [comment]
@bignamehere 

Looks perfect. Merge away.

**Comment by bignamehere** [comment]
Merged here: [b6aef19](https://github.com/USDA-FSA/fsa-style/commit/b6aef19f8975ab47742ae845141b5aa44539915d)

**Comment by francisrupert** [comment]
Reopening to fix a minor bug. @francisrupert will fix.

**Comment by francisrupert** [comment]
closed via 030b334

**Comment by francisrupert** [comment]
Moved to `develop`

**Comment by bignamehere** [comment]
wrong issue number posted here. Ignore following commit message as it is unrelated to this issue.

"update and simplification of Select Multi [amends #178]"
