### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#18]
USDWS typography provides a robust foundation for FSA to make design decisions on which aspects to use, ignore, extend, modify, and/or re-categorize.

### Key Tasks

- [x] **Fonts**: Merriweather **and** Source Sans Pro.

- [x] **Font Size Scale**: adopt current USWDS scale / change / add / etc.? Think carefully about *vertical rhythm* and *hierarchy*. 

  - [x] **Units**: `em`, `rem` (with fallback), px
  - [x] **Line Height**:

- [x] **Spacing**: again, it's all about vertical rhythm.

  - [x] **Sizing units**: (e.g., create a `$size-base` and base additional magic numbers off that; such as, `$size-small: $size-base * 2`. Are these `px` or `em` or..?)
  - [x] **Margins**: Top *and* bottom, or just bottom, or...?

- [x] Helpers, (e.g., `fsa-text-XX` or something to be addressed in #40)
- [x] `.usa-font-lead` extension
- [x] Lists

**Comment by brianmillsUX** [comment]
Minor edits made to enhance grammar and clarity; in-line with team discussion and great start!
