### ISSUE TITLE
Setup FSA-Style using Webpack

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#209]
- [x] Install fresh version of Webpack
- [ ] Setup FSA Style file structure (retaining `src` as is)
- [ ] Configure dependencies & [Grunt-equivalent tasks](https://github.com/USDA-FSA/fsa-style/blob/master/Gruntfile.js)
  - [x] clean
  - [x] copy (primarily to bring in USWDS assets).
  - [x] watch
  - [x] [browsersync](https://browsersync.io/)
  - [ ] prettify (html)
  - [x] style-loader / css-loader
  - [x] SCSS source map
  - [x] [stylelint](https://stylelint.io/)
  - [x] min (i.e. `fsa-style.css` _and_ `fsa-style.min.css`)
  - [ ] postcss (and associated plugins)
      - [x] autoprefixer
      - [ ] pixrem
      - [ ] postcss-quantity-queries
  - [ ] usebanner (currently used for version comment line of [`fsa-style.[min].css`](http://usda-fsa.github.io/fsa-style/css/fsa-style.min.css))
  - [ ] Compress to published ZIP
  - [ ] What else excites us?
      - [ ] [prettier](https://prettier.io/), possibly in place of `prettify`
      - [ ] [CSS Next](http://cssnext.io/postcss/) (unlikely, but worth exploring)
      - [x] [hot-module-replacement](https://webpack.js.org/concepts/hot-module-replacement/). Not exactly a "live-reload" (or browsersync) analog, but still interesting
      - [ ] Basic "includes" to piece together Kitchen Sink (index.html) listing (future: templating etc)
- [ ] Test
- [ ] Publish to new branch

**Comment by francisrupert** [comment]
@bignamehere,

This definitely is the next logical step, and not just because of your environment challenges. Let's make sure anything Webpack is in lock-step with @arosenblum and @atdiff to optimize and prevent redundant work as it relates to Topsoil.

For that matter, there's no reason why @arosenblum and @atdiff shouldn't feel free to work in this repo in their own branches, or even carefully track your branch. Good opportunity for peer reviewing / paired programming.

Thoughts everyone?

**Comment by francisrupert** [comment]
@bignamehere,

Note I've edited the task list of [this issue's initial post](https://github.com/USDA-FSA/fsa-style/issues/209#issue-294560044) just to be more specific.

**Comment by bignamehere** [comment]
I was able to get a clean build from the following Test Branch. a21e888 

- npm install -g yarn
- cd to project directory
- npm install
- yarn build

This will build the 'dist' directory that somewhat match what we want in FSA-Style from a CSS perspective. 

Need to work on doing the same for JS files, and also including all of the original src files from the normal FSA-Style repo.

**Comment by bignamehere** [comment]
Current status: HTML, CSS, SCSS, Images, and Fonts all build correctly. Working on JavaScript, and running into loader issues with jQuery. 03570f6

**Comment by bignamehere** [comment]
@atdiff & @francisrupert  - I was able to fix the last broken build, which as the jQuery module issues. It requires jQuery as an dependency, so it will be good to get rid of jQuery soon.

here is the latest: a00c2f3

**Comment by bignamehere** [comment]
@atdiff & @francisrupert 

It looks like the build is somehow preventing certain JS to load, even though they are in the bundle.js file. I thought it was related to the jQuery loader issue because the Docs Nav is not performing as intended, but then I noticed it wouldn't call a console.log() in various places either. @atdiff any ideas why the JS would bundle in this way?

**Comment by atdiff** [comment]
I'll take a look at it

**Comment by bignamehere** [comment]
@atdiff any luck on this one? I have been searching for a while without finding why some of the code IS being bundled, but unable to be reached by the application when it runs.

Thanks for the help!

**Comment by atdiff** [comment]
Ended up being an easy fix.  If you change the "start" script in the package.json to add "--hot" and "--inline", it works.
`"start": "SET NODE_ENV=development & webpack-dev-server --hot --inline",`

**Comment by bignamehere** [comment]
@atdiff awesome! I wasn't even thinking it was part of the startup script. Thanks for taking a look.

**Comment by atdiff** [comment]
It didn't occur to me at first either.  Once I started putting breakpoints in and those weren't even getting called, I started wondering about the console error regarding the "hot module replacement" not being enabled.  Then found the answer to that was with the two options.

**Comment by bignamehere** [comment]
@francisrupert  There are tools you listed above that I am getting configured into the build process, but some of them, I am not sure how to use or verify that it is working. Such as stylelint... I included it in this version  d97773d  but am not sure how to verify that it is working to the needs of the project.

**Comment by bignamehere** [comment]
updated webpack to utilize separate configs for production and development as there were some issues with dev builds deleting directories.

see 55283db

**Comment by bignamehere** [comment]
Completed Webpack 4 update, [referenced here](https://github.com/USDA-FSA/fsa-style/issues/245).

**Comment by bignamehere** [comment]
Closing this issue, but cross-referencing it in the [Webpack Version 4 upgrade issue](https://github.com/USDA-FSA/fsa-style/issues/247).
