### ISSUE TITLE
Reconsider button variations

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#232]
@bignamehere 

Much like the exploration to reduce Typefaces (#229), I say we consider the same for **buttons**.

## Problem

The number of styled variations available in `fsa-style` might be problematic, and we both kinda knew this anyway.

1. **PCP User testing** reveals confusion surrounding `--secondary` (dark gray) and `--alt` (blue border, white bg) throughout the PCP experience.
1. **Feedback and questions** from consumers (development, stakeholders, etc) of `fsa-style` continue to speak to uncertainty of (much like users) when to use `--secondary` and `--alt`. 
   * Meanwhile, `--flat` and `--tertiary` don't exhibit this problem. The implicit purpose of those two variations has been fairly intuitive to both groups alike.

## Discussion / Proposal

**Bite the bullet and simplify.** 

1. **Primary:**
   * The one main action in its context. 
   * Generally one _per context_.
1. **Secondary:** 
   * Nearly anything else. 
   * Possibly multiple per context.
   * Consider restyling _from_ dark gray background to the current `--alt` style (or do we want to play with a bit more?)
1. ~~~**Alt:** remove this variation.~~~
1. **Tertiary:** 
   * Generally reserved for _destructive_ action, e.g. "You sure about that?"
1. **Flat:**
   * looks like an `<a>`, functions like a `<button>`

### Outcomes

* 90% of the time, it's an _easy_ decision of "Primary or Secondary?" Beyond that, I'm confident it will be obvious when to use Tertiary (destructive) and Flat - especially if paying attention to its Documentation.
* If nothing else, _authoring_ documentation will be a snap, and nearly remove questions of _"what variation do I use for..."_ -- which has been the number one question as we've iterated upon the Design System.

## Super quick exploration screenshot

**Current** | **Reduced**
------------ | -------------
![image](https://user-images.githubusercontent.com/1165933/38106453-a06b389a-3354-11e8-88b8-ffb24fb44b8a.png) | ![image](https://user-images.githubusercontent.com/1165933/38106590-143a9b80-3355-11e8-9449-90f8115d2c43.png)

**Comment by bignamehere** [comment]
@francisrupert 

I like the proposed solution of removing the ALT version of the button. I believe the only applicable area for this button is to have "button shape" for an action to perform something in a destructive way. There was always cognitive dissonance from Developers as to which button to use, and similar reactions or perceived reactions (via the Business) from Users. 

I believe only using a Flat button for anything destructive is appropriate, and the grey secondary button can serve all other purposes for general, non-primary actions.
