### ISSUE TITLE
Disabled State of components - 508 Contrast Issues

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#242]
There are a number of components that do not pass Color Contrast ratio testing in the Disabled State. The below list includes the items that need to be updated.

Disabled Versions:

- [ ] Primary Button
- [ ] Secondary Button
- [ ] Tertiary Button
- [ ] Flat Button
- [ ] Checkbox - Selected
- [ ] Checkbox - Unselected
- [ ] Radio Button - Selected
- [ ] Radio Button - Unselected
- [ ] Textarea
- [ ] Multiselect
- [ ] Labels
- [ ] Badges

**Comment by francisrupert** [comment]
Discussion needed. In the meantime, the official quote to think on, officially from https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

(Emphasis mine)

--

....has a contrast ratio of at least 4.5:1, except for the following....
* Large Text....
* Incidental: Text or images of text that **are part of an inactive user interface component**....
* Logotypes....
