### ISSUE TITLE
Aria-Required on Form Input Fields

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#243]
The Design System current has `aria-required="true"` on Form Input fields that also have the Required "label" on them. Should we be using aria-required or not, as browsers that don't support HTML5 would benefit from it's use.

This can be seen here: http://usda-fsa.github.io/fsa-design-system/components/form-fields/

@francisrupert let me know your thoughts

**Comment by francisrupert** [comment]
Yes. The `aria-required` attribute "announces" that is required, while the `.fsa-field__label-desc` _visually_ does so. If both are perceived, then that redundancy is perfectly fine. Additionally, for those screenreaders that may not fully support ARIA attributes the 'Required" text contained _within_ the `<label>` element further drives it home.

Close if no further discussion needed.

**Comment by bignamehere** [comment]
@francisrupert - Currently, FSA Style does not use aria-required="true", so shouldn't we keep this issue open so that it can be updated as such in the index.html? Or are you saying it isn't needed in the example on index.html?

**Comment by francisrupert** [comment]
You're correct, I'd assumed it was on the kitchen sink listing, but I see now it's only on the Design System.
