### ISSUE TITLE
Create Utility Class for Components to use

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#258]
There are a handful of JavaScript components that utilize the same or similar utility methods, and we need to create a better way to [stay DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). For each of the components listed below, create a utility method inside of an FSA Utilities Class.

- [x] Growl
- [x] Modal
- [x] Nav Global
- [x] Select Multi
- [x] Stepped Control
- [x] Whiteout
- [x] Spinbox

Once the Utility Class is developed and tested, Create a new issue for each component to update the code.

**Comment by bignamehere** [comment]
@francisrupert 

I have created a Helper.js file filled with awesomeness and JavaScript madness. I updated all of the above listed files, using the WP4 version, so I need some help testing this feature before it can be moved into develop.

Let me know if you see any errors or issues.

Thanks!

**Comment by francisrupert** [comment]
@bignamehere,

This is awesome, just as pictured. I [merged these updates](https://user-images.githubusercontent.com/1165933/42219240-e28852da-7e90-11e8-88d9-26a6f3db97ba.png) to a branched version of the most recent `develop` (local only), tested each JS-impacted component, and **they all appear good** -- save for one minor Growl bug (details below). 

Come check out everything at my desk to see them all in action and validate if you want.

Reassigning this issue back to you.

### Growl Bug

The "Centered" version is not gaining focus. [View a screencast](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/XCut%20-%20UX/1.%20Strategy%20and%20Design%20Guide%20-%20FSA%20and%20USDA/screencasts/growl-bug__centered-not-gaining-focus.webm).

### Spinbox

I see that you also applied them to my Spinbox addition; shall I assume that implicitly completes my [Spinbox Review Request (#180)](https://github.com/USDA-FSA/fsa-style/issues/180#issuecomment-400798668)? I want to make sure you bless my Vanilla-ized Spinbox JS.

**Comment by bignamehere** [comment]
@francisrupert I fixed the bug in Helper.js related to `hasClass` and also added a couple more utility methods that were in Spinbox, as they might be useful in other components.

Things tested fine on WP4, can you test and push to develop if they look good in the Grunt version?
