### ISSUE TITLE
Doc nav item hover in IE11 vs Edge vs EOMB

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#273]
### As reported

> "...doesn’t show the navigation drop downs in Edge but it works in Chrome.  In Edge, it shows the arrow but no child menu.  In IE, it shows no arrow or child menu."

### Details

Not a bug for _usage_ of `fsa-style`; is solely about the [usda-fsa.github.io/fsa-style](http://usda-fsa.github.io/fsa-style/)'s doc menu - specifically `docs__primary-nav-item--sub:hover`.

This was sort of intentional as _progressive enhancement_, though @francisrupert didn't stick the landing. It can be better.

### Screenshot showing correct behavior/rendering

![image](https://user-images.githubusercontent.com/1165933/49455340-9f121c80-f7ac-11e8-99c8-a494e19b796c.png)

*EOMB = Every Other Modern Browser

**Comment by whatnextjamie** [comment]
@bignamehere It looks like this one has already been resolved. Agree to close?

**Edge on hover**
![image](https://user-images.githubusercontent.com/30541689/184245143-c028ddac-843a-4a1a-91a6-2424b1bf182f.png)

**Chrome on hover**
![image](https://user-images.githubusercontent.com/30541689/184245318-6f7e1b24-5d58-4c3f-9b8a-ed07d97f5193.png)

**IE11 no longer supported**

**Comment by bignamehere** [comment]
@whatnextjamie It doesn’t need to work in any IE, but it does need to work in Edge. From those screenshots it looks like it’s working, but check behavior in all breakpoints too.

**Comment by whatnextjamie** [comment]
Working as expected at all breakpoints in Chrome and Edge.
