### ISSUE TITLE
fsa-growl (and fsa-modal) images

### ISSUE THREAD

**Issue by atdiff** [USDA-FSA/fsa-style#276]
Currently with fsa-growl, an img tag is used to supply the close button. Wondering if it would be better to have these as background-image so that they're automatically included with fsa-style. Webpack would automatically pull in the necessary images as a part of the build process. The images could still be overridden per project as needed.
**Reasoning:**
I have a custom JS module that has the growl notification HTML with the close image src reference. The HTML is converted to JavaScript when bundled into it's own module. When included in my project, it doesn't get parsed through the html-loader since it's JS. And during the project build process, webpack doesn't see the <img> tag to know to pull in the image file. Currently, the workaround is to have a custom CSS class that references the file just so it will get pulled into the bundle, but this isn't ideal. If the project used a CSS tree-shaking plugin, this class would be removed since it's not really referenced anywhere.
If a background-image were used, webpack would know to pull the file in without any extra effort. We could use a require statement instead, but I'm trying to stay away from littering the code with too much of that.
Thoughts?

**Comment by francisrupert** [comment]
**Status:** changed to CSS-based close icon over inline `<img>`. Still backwards-compatible for anyone still using inline `<img>`.
