### ISSUE TITLE
npm dependency

### ISSUE THREAD

**Issue by atdiff** [USDA-FSA/fsa-style#277]
Is npm needed as a dependency in the package.json?

**Comment by francisrupert** [comment]
@bignamehere,

Doing a [Git Blame on that line](https://github.com/USDA-FSA/fsa-style/blame/9dfa41107960f1889385fee5945d1759a4b2a270/package.json#L53) shows you added it when you [Vanilla-ized the Stepped Control](https://github.com/USDA-FSA/fsa-style/commit/a8b94aec5cb2e18cc142ef61fdbdaba00858cefb) component (#237).

**Comment by bignamehere** [comment]
@atdiff @francisrupert  It shouldn't be.
