### ISSUE TITLE
Textfields: response states

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#30]
* [x] Positive
* [x] Negative
* ~~"Helpful message"~~ (will be added in forms **component** creation)

Ref #27 

Initially inspired by USWDS equivalent: https://standards.usa.gov/form-controls/#text-inputs

![image](https://cloud.githubusercontent.com/assets/1165933/15027442/68692380-1209-11e6-9825-64c180a6ff79.png)

**Comment by brianmillsUX** [comment]
Including the addition of symbols (e.g., an "X" for an error and check mark for success) will help clarity.

**Comment by francisrupert** [comment]
Closed via cb10bfcf269ee8e182433311119e38c415d8806a
