### ISSUE TITLE
Esc keypress: hide Nav sub-menu

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#305]
When the nav is in the state seen in screenshot below, keypress of `esc` shall hide expanded sub-menu.

It shall retain focus to the item that initiated the expansion (e.g. "Admin"), particularly when focus was on one of sub-menu's children (e.g. "Technology Plans").

![image](https://user-images.githubusercontent.com/1165933/56499146-b9823380-64ca-11e9-9b54-caa44fe5919c.png)

**Comment by bignamehere** [comment]
Added keydown event to the global nav to check for escape key and exit menu. closing as per a2837dc
