### ISSUE TITLE
Date Picker: Research and prototyping

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#307]
There is a need for a Date Picker component that augments single Input field to enter a date, and utilizes a calendar view to make a date selection. The component will need to be fully compliant with 508, and utilize keyboard commands represented below.

In reference to the work being performed on https://github.com/USDA-FSA/fsa-prototype-kit/issues/15)

Keyboard Requirements:

Press the LEFT and RIGHT arrow keys to navigate the row by week day.
Press the HOME and END keys to jump to the beginning or end of the current row.
Press the UP and DOWN arrow keys to navigate between weeks on the same week day.
Press the PAGEDOWN and PAGEUP keys to navigate backwards or forwards by month.
Press ALT+PAGEDOWN and ALT+PAGEUP to navigate backwards or forwards by year.
Press the ENTER key to activate the selected date.
Press ESCAPE to close the calendar without making a selection.

Tasks to be broken out into individual Git Issues:

- [ ] Ensure it works sans-Webpack (tech stack-agnostic)
- [ ] Ensure Keyboard functionality is maintained

**Comment by francisrupert** [comment]
@bignamehere 

Current *WIP* styled state seen in screenshot below. I may not get back to this task today as I'll be on spa ref app mostly. If you're working through the JS on your own branch, you'll want to merge in my branch (`experimental/date-picker`).

I'm mostly happy with the style, but definitely will continue to refine. Once I'm really really satisfied with its style, and you've also had a chance to peer-review its look and feel, we'll work through the *dual approach* of its non-`fsa-style` version (for legacy use) and actual `fsa-style` component use of that abstracted version.

![image](https://user-images.githubusercontent.com/1165933/57775875-acc8b800-76e3-11e9-8922-797a2ee6f41d.png)

**Comment by bignamehere** [comment]
@francisrupert 

I pulled down your version and integrated my JS changes that include the First Day of Week customization. date-picker.html has the settings. I will take a look at the L&F and we can discuss.

**Comment by bignamehere** [comment]
@francisrupert  After looking it over I think the only adjustment that I would make is the centering of the numbers. Most calendars centered align numbers, including iOS, Google, Microsoft, etc... so I think that would be a good adjustment to make. Also, I don't feel like the hover state BG color represents the Design System. I don't see any other components with a hover state that is that aqua color. I would go with $color-fsa-secondary-900 as it is used for a hover on components like the stepped tabs and text links. The only other hover states that I see are for button groups and they change to light grey, which I can see avoiding.
