### ISSUE TITLE
Date Picker: broader keying user input support

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#309]
### Task
Support manual entry of `mmddyyyy`, such that manually keying `05141975` (no `/`) resolves to `05/14/1975`. 

This task is purely about attempting to autoformat more common user-created strings, though may not be able to predict every combination.

### Incorrect Examples
* Currently keying in `05141975` resolves to `09/05/514`.
* Currently keying 5-1-2019 resolves to `01/05/2019`

**Comment by francisrupert** [comment]
Triaged to https://github.com/orgs/USDA-FSA/projects/9

**Comment by francisrupert** [comment]
@bignamehere,

I've renamed this issue and added a few details to support this morning's discussion, to better track against your work on it.

**Comment by bignamehere** [comment]
@francisrupert @arosenblum @atdiff 

Can you all take a look at the issue/309 branch and provide your input/testing. The goal was to allow for as many date formats as possible without introducing possible errors. Here are the formats that should work and reformat correctly based on my testing:

MMDDYYYY
MM/DD/YYYY
M/D/YYYY
MM/DD/YY
MM-DD-YYYY
M-D-YYYY
M-D-YY
MM.DD.YYYY
M.D.YYYY
MM.DD.YY
M.D.YY

Also, I started down the path of allowing a way for a Developer to pass in a callback method for date validation. Ideally, this would allow for external JavaScript validation to run before the reformatting of date and selection of the date within the calendar before it opens. I haven't determined where this code could be used within the fsa-date-picker.js, but I am hoping to add that functionality at some point.

**Comment by francisrupert** [comment]
@bignamehere,

I just remembered there _is_ something akin to that. Look for `fsa-date-control__btn--date-is-valid`, and perhaps explore how that's used and if it's close. 

We're not directly styling with it, though we could. Add something like `.fsa-date-control__btn--date-is-valid {  background-color: green;}` to see it action. Would also be nice if it's possible to converely apply `fsa-date-control__btn--date-is-not-valid`.

e.g. here's first instance of it...

https://github.com/USDA-FSA/fsa-style/blob/b5773f7005d4214b3fb910963237a22d3f9a5441/src/js/vendor/fsa-date-picker.js#L2593-L2595

**Comment by francisrupert** [comment]
@bignamehere: Awesome work, goes a long way. I stress-tested the heck out of it all morning. 

@arosenblum and @atdiff: I've placed this at a **[Sharepoint URL](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/XCut%20-%20UX/8.%20Projects/fsa-style/branches/feature/date-picker/scratch.html)** so you can test (if only so you don't have to git pull the branch and build). _Please throw everything you've got at it and respond to this Issue thread._

**Comment by bignamehere** [comment]
closing this issue as previous commit addresses main problem.
