### ISSUE TITLE
Date Picker: support input[type=date]

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#311]
Currently only supports `<input type="text">`, and does nothing with `<input type="date">`. I suspect this could be a CSS adjustment too, not just JS.

**Comment by francisrupert** [comment]
Triaged to https://github.com/orgs/USDA-FSA/projects/9

**Comment by bignamehere** [comment]
@francisrupert It seems this would be something we document as a Do Not Use, because it would directly interfere with our approach and calendar, and create behavior that we don't document. 

thoughts?

**Comment by francisrupert** [comment]
@bignamehere,

Agree. We'll also make sure our examples only use `type="text"` (which they do). Closing.
