### ISSUE TITLE
Date Picker: “Disabled Date” title attr

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#312]
### Bug
Title attribute value for disabled days is meaningless and duplicative, e.g. `Disabled date : Disabled date : Disabled date :`. Screenshot below.

![image](https://user-images.githubusercontent.com/1165933/58359257-28dfa000-7e48-11e9-8a36-e03fc0e486ed.png)

**Comment by francisrupert** [comment]
Triaged to https://github.com/orgs/USDA-FSA/projects/9

**Comment by bignamehere** [comment]
fixed and closing as per 6d2a006
