### ISSUE TITLE
Date Picker: title attribute on "Today"

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#315]
Other calendar "nav:" elements have `title` attribute, but "Today" has an _empty_ `title` attribute. That is, the JS does add the attribute, but it's blank. Screenshot below demos hovering "Previous Month".

![image](https://user-images.githubusercontent.com/1165933/58480544-2d45da80-8120-11e9-833a-de9d06d984b9.png)

**Comment by francisrupert** [comment]
Triaged to https://github.com/orgs/USDA-FSA/projects/9

**Comment by bignamehere** [comment]
Bug found... the original code used the titles array value for for the text, but didn't have anything specified for the title, like the other buttons.

**Comment by bignamehere** [comment]
This is fixed and can go with next release.
