### ISSUE TITLE
Date Picker: Firefox bug

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#317]
### Expected Behavior

1. tab to focus on calendar icon (`.fsa-date-control__btn`).
1. press `spacebar`.
    * calendar exposed

### BUG Behavior

In **Firefox**.

1. tab to focus on calendar icon (`.fsa-date-control__btn`).
1. press `spacebar`.
    * calendar exposed and _**imediately closes it**_

Have not reproduced this bug in other browsers.

**Comment by francisrupert** [comment]
Triaged to https://github.com/orgs/USDA-FSA/projects/9

**Comment by bignamehere** [comment]
Found code that was performing a check for spacebar keycode 32, that seemed to be causing the issue in FF. I tested in FF, IE, and Chrome and it appears to be working properly now.
