### ISSUE TITLE
datepicker.js > fsa-date-picker.js

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#329]
1. Undo naming `datepicker.js` to `fsa-date-picker.js`, back to `datepicker.js`.
1. `/src/js/vendor/fsa-date-picker.js` requires in `src/js/vendor/datepicker.js`.
1. End result is the same: `/dist/js/vendor/fsa-date-picker.js`.

**Comment by francisrupert** [comment]
@bignamehere Our initial stabbing WIP on branch `issue/329`. Primary remaining nice-to-have is suppress `datepicker.js` from being copied over via grunt to `dist`.

**Comment by francisrupert** [comment]
@bignamehere,

Ignore my https://github.com/USDA-FSA/fsa-style/issues/329#issuecomment-503205448 and ignore any attempts we made on branch `issue/329`.

**Comment by bignamehere** [comment]
@francisrupert 

I was able to get what I believe our desired result to work by using a combination of clean, copy, and clean again during a normal build.

Here is how it works:

- Using `copy` I am creating a new version and renaming it to `fsa-date-picker.js`
- Then the normal `copy` method runs to copy all content to the `dist`
- Then I perform a secondary `clean` method that deletes the `datepicker.js` file from `dist`

I am sure there is plugin that performs this functionality, but I wanted to see if we can use our existing tooling and get it to work. It seems to be working well.

**Comment by francisrupert** [comment]
Perfect.

**Comment by bignamehere** [comment]
@francisrupert Adding one more thing to the clean method, then will merge back to develop

**Comment by bignamehere** [comment]
updated, merged, and closing
