### ISSUE TITLE
Test Local Environment 

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#38]
## Summary

This issue is specifically established to provide @brianmillsUX (and anyone else who wants) a refresher on cloning this repo and testing the build process on his machine.

This will act as a precursor to solidifying **#8** and informing **#16**, **#17**, and **#12**.

## Action

* @brianmillsUX: Follow instructions below and report back as a comment below.
* @francisrupert: Provide support as Brian does so.
* @jeremyhaas, @edlyman: Lurkers.

## Step-by-step Instructions

I know it's been a while since you've done this, so I've hopefully added sufficient detail to re-familiarize yourself with working with the GitHub GUI app and command line. It's quite simple as a flow, though I've intentionally detailed quite a bit for the benefit of anyone with little experience working this way -- if only to draft out documentation in the interest of the issues mentioned above.

### Summary

Once you've done this once or twice, it's second nature. I've noted likely one-time-only steps with a `*`.

1. Clone repo `*`
1. Switch to appropriate branch
1. Open in Git Shell (Command Line)
1. Install Dependencies `*`
1. Build it and view in browser

### Clone Repo

**1**. View https://github.com/USDA-FSA/fsa-style

**2**. Click on the **Clone** button:

![image](https://cloud.githubusercontent.com/assets/1165933/15195175/41eff958-178c-11e6-9ec9-b26a8ac11c47.png)

**3**. This should open it in GitHub desktop app (if it doesn't let me know and we'll sort it out).

**4**. It will prompt you for a location to save to. Choose a location.

**5**. You should now see "fsa-style" as a listed repo on the left, looking something like...

![image](https://cloud.githubusercontent.com/assets/1165933/15195534/e6998518-178d-11e6-825e-77fd4edab7cd.png)

### Switch Branch

By default, it'll be on the `master` branch, which is basically empty. So let's get you to most relevant working branch:

**1**. Choose `feature/visual-index`

![image](https://cloud.githubusercontent.com/assets/1165933/15195752/dccd10f8-178e-11e6-97f3-2a0aa15c3e33.png)

### Open in Git Shell (Command Line)

Now we're to work with it in the command line.

**1**. Via the "Gear" icon, select `Open in Git Shell`

![image](https://cloud.githubusercontent.com/assets/1165933/15195799/115030ee-178f-11e6-9036-3b6503c34519.png)

**2**. A shell will open and you should see something that looks like...

```sh
username@machine-name  ~/path/to/fsa-style (feature/visual-index)
```

**3**. You're now viewing the directory.

**4**. Let's find out what's in it. Type `ls` (command for "list directory contents") and hit enter. That's the letter `l`, not the number `1`. Should generally look like...

```sh
CONTRIBUTING.md  LICENSE.md     package.json  src/
Gruntfile.js     node_modules/  README.md
```

**5**. Type `ls -l` and hit enter (command for "long list"), giving you more detail and more scannable, e.g.

```sh
-rw-r--r-- 1 1049089  519 May 11 15:36 CONTRIBUTING.md
-rw-r--r-- 1 1049089 4858 May 11 15:36 Gruntfile.js
-rw-r--r-- 1 1049089  679 May 11 15:36 LICENSE.md
-rw-r--r-- 1 1049089  989 May 11 15:36 package.json
-rw-r--r-- 1 1049089 2762 May 11 15:36 README.md
drwxr-xr-x 1 1049089    0 May 11 15:36 src/
```

**6**. We'll refresh you on other commands and subcommands at a later date.

### Install Dependencies

You're currently viewing the cleanest state. Here's a very brief summary of key items:

```sh
Gruntfile.js  # Core tasks to build assets
package.json  # Lists design and dev dependencies
src/          # Originating source assets that Grunt will build to dist/
dist/         # The distribution. End result of assets built (you won't see this initially).
```

**1**. "Installing dependencies" means "looking in `package.json` to see what this project will use."

**2**. You'll enter an `npm` command that spends several minutes installing those dependencies. When you submit the below command, you'll see a long scrolling list of stuff happening. Be patient with it.

**3**. Type `npm install` and hit enter, and just wait a few minutes.

**4**. If the command line looks like it's not successful, it should let you know. In which case, you should let me know.

**5**. It has created a `node_modules` directory with dependencies listed in `package.json`. Hit `ls` to see `node_modules` directory.

### Build it and view in browser

Let's built it now!

**1**. Ensure you're in the correct directory. The most current line in Git Shell should look like this:

```sh
username@machine-name  ~/path/to/fsa-style (feature/visual-index)
```

**2**. Verify you're in `fsa-style` on `feature/visual-index` branch.

**3**. Now we're gonna send an `npm` command that asks `Gruntfile.js` what tasks to run.

**4**. After you enter the below `npm` command, you'll see a series of tasks being run. A *successful* result will end with the browser opened up to the **Visual Language** `index.html`.

**5**. If that's not the result, try `grunt` in place of `npm start`. If nothing works, summarize your experience as a comment on this issue thread and we'll get together and troubleshoot.

### What just happened?

Here's a simplification of what has occurred:

**1**. Clean out the `dist` folder (if exists).
**2**. Import <abbr title="US Web Design Standards">USWDS</abbr> assets (CSS, IMG, JS, etc) to `src`.
**3**. Build HTML, CSS, JS, IMG, etc to `dist` folder.
**4**. Run server and open http://localhost:3000/ in browser.
**5**. Watch for changes and refresh browser (we'll cover doing this in near future).

### Quitting

The command line will show this when it's running...

```sh
Running "watch" task
Waiting...
```

Several ways to cancel, or quit, it:

**1**. Hit `Ctrl C`
**2**. Closing Git Shell, e.g. via app `X`, in which case it'll prompt you if you want to kill the running process.

**Comment by francisrupert** [comment]
@brianmillsUX,

I've updated the initial post of this issue and assigned it to you. Enjoy!

**Comment by brianmillsUX** [comment]
@francisrupert - thank you so much for this wonderful walk-through! As we discussed yesterday, some of the expected processes aren't triggering (either at all or as planned). If you have a few minutes, let's set aside some time ASAP to walk you through what I'm doing/experiencing so we can troubleshoot. If we're lucky, my bet is that it's something that we can modify slightly so everything else flows right. :)

**Comment by brianmillsUX** [comment]
Updates:

1) successfully updated al relevant system software in support of GitHub process validation testing

2) GitHub process validation testing was almost a complete success; minor sync conflict detected

3) Additional research, review, and test is actively underway to solve minor conflict and wrap sync
