### ISSUE TITLE
Reflect more accurate value of aria-current

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#397]
Currently, the ARIA attribute to indicate the current step in the stepped tabs component uses a value of "true". I propose using the value of "step" for this indication, as it more accurately defines the status of the component for Users with assistive technologies.

Current:
`aria-current="true"`

Proposed:
`aria-current="step"`

See W3C documentation: https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#aria-current

![image](https://user-images.githubusercontent.com/2124049/70000272-4ccf1d00-1520-11ea-8cf1-66e7a3366caa.png)

**Comment by francisrupert** [comment]
Good call. I’d initially landed on “true” as a safe value so as not to presume it is *always* a “step.”

I’d update it to “step” and provide docs that allow for implementer to make a judgement call on if it’s actually a “page”.

**Comment by francisrupert** [comment]
Extending this issue to _all_ components with `aria-current` attribute, e.g. Stepped Tabs, Pagination, Content Tabs.
