### ISSUE TITLE
Enable dynamic disabling/enabling Date Picker

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#435]
(This is a placeholder issue, with background details forthcoming to be completed by @arosenblum, initiated with commit 9f14cc1b343a44ab6309a8d79f8bda1fb220ed87)

**Comment by arosenblum** [comment]
Background:  When programmatically enabling or disabling a datepicker, the necessary corresponding CSS attributes and DOM nodes were not all being toggled.  In particular, the "disabled" attibute was not being removed on enablement of the datepicker.

**Comment by francisrupert** [comment]
Resolved by 9f14cc1

**Comment by francisrupert** [comment]
General FYI: since the tab formatting was automatically changed from 4 to 2 spaces, most diff views were not helpful. VS Code actually did a smarter job of showing the diffs (ignoring the 4 vs 2 spaces). 

For posterity's sake (and as a "pseudo-blame"), here are the specific **additions** (there were no other changes): 

https://github.com/USDA-FSA/fsa-style/blob/9f14cc1b343a44ab6309a8d79f8bda1fb220ed87/src/js/vendor/datepicker.js#L2757

https://github.com/USDA-FSA/fsa-style/blob/9f14cc1b343a44ab6309a8d79f8bda1fb220ed87/src/js/vendor/datepicker.js#L2765-L2768

And a screenshot of the entire diff with those two updates in context.

![image](https://user-images.githubusercontent.com/1165933/82481948-b8d81a00-9a9b-11ea-8ce4-606ce2d1a6b7.png)
