### ISSUE TITLE
Bug: Tabs active state while in focus

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#454]
### Summary 

With the introduction of `:focus-visible` in `2.5.2`, #445, a bug was introduced in the [Content Tabs](https://usda-fsa.github.io/fsa-design-system/components/content-tabs/).

### Tasks

- [x] Fix for Content Tabs
- [x] Test
- [x] Identify other possible instances of this bug (i.e. those that use `outline` property.

### Culprit

Collision between Tab's active state using `outline` property with `:focus-visible` suppressing it *while in focus*. Blurring away from active tab brings it back.

#### GIF

![D36A8DCE-C63C-42D0-8E60-1AC0930EA046](https://user-images.githubusercontent.com/2124049/104213630-23a7de00-53fc-11eb-8d61-feb32dfe59eb.GIF)

### Video with voiceover describing bug

https://user-images.githubusercontent.com/2124049/104213681-315d6380-53fc-11eb-8368-c08ffabba960.MP4

**Comment by bignamehere** [comment]
@francisrupert I tested the Snagit capabilities and added both an animated GIF and video of the screencast for the issue. Feel free to keep what is most valuable.
