### ISSUE TITLE
Icon set: Research and Propose

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/fsa-style#49]
### Summary

Research and analyze Icon set alternatives.

* SVG vs Icon Font 
  * initial assumption is Font-based method poses network challenges, and cumbersome implementation)
* SVG Options
  * `<img src="path/to/icon.svg">` vs...
  * SVG Sprite vs...
  * SVG Inline

### Icon Evaluation

Explore the following icons with `fsa-style` in context of current components and layouts. In other words, these are my initial presumptions of most common icons (not definitive and likely will change).

* Settings / Gear
* Calendar
* Alert
* Error
* Success
* Lock / Secure / Shield
* Check Circle 
* Check Square (not necessarily meant to replace [checkbox](https://usda-fsa.github.io/fsa-design-system/components/checkbox/))
* Layers (including mapping)
* Chevron / Caret (down|up|right|left|Double)
* Arrow (possibly redundant or superceded by Chevron)
* Close / X
* Clock
* Dots (vertical ellipsis, aka "Actions")
* Filter
* Help / "?"
* Account / User
* Home
* Information / "i"
* Zoom / Magnify / Search
* Plus / Minus
* Bell
* Sign out / Sign in (Log)
* Expand / Collapse

#### Current Icons

Some current components have a built-in icon (primarily via CSS background or inline) and will weigh heavily in this evaluation. Most can be seen in https://github.com/USDA-FSA/fsa-style/tree/master/src/img

* [Date Picker](https://usda-fsa.github.io/fsa-design-system/components/date-picker/)
* [Select](https://usda-fsa.github.io/fsa-design-system/components/select/)
* [Spinbox](https://usda-fsa.github.io/fsa-design-system/components/spinbox/) 
* [Search](https://usda-fsa.github.io/fsa-design-system/components/search/)
* [Growl Notification](https://usda-fsa.github.io/fsa-design-system/components/growl)
* [Inline Alerts](https://usda-fsa.github.io/fsa-design-system/components/alerts)
* [Modal](https://usda-fsa.github.io/fsa-design-system/components/modal)
* [Pagination](https://usda-fsa.github.io/fsa-design-system/components/pagination)
* [Global Nav](https://usda-fsa.github.io/fsa-design-system/components/top-nav)

### Criteria
1. Overcome need to identify every possible icon across current or new FPAC apps.
1. Licensing
1. Build Tooling
1. Requires little-to-no custom creation
1. Breadth and depth of selection
1. Style-able, primarily fill color
1. Works seamlessly with established [Size and Space](https://usda-fsa.github.io/fsa-design-system/visual-style/size-and-space/), implicitly creating icon sizing standard.
1. Variations: filled-in, outline, rounded, etc.
1. Compatibility with current Design System components; requires (ideally) no updates to current Design System parts.
1. Legibility
1. Accessibility
1. Simplicity and minimized ambiguity
1. Browser Support

#### Narrowed-down 

1. [FontAwesome](https://fontawesome.com/)
1. [Material Baseline](https://material.io/resources/icons/?style=baseline)

#### Removed from consideration
1. ~~[Iconic](https://useiconic.com/open)~~
1. ~~[Material Community](https://materialdesignicons.com/)~~
1. ~~[CSS](https://css.gg/)~~
1. ~~[Icomoon](https://icomoon.io/#preview-free) (PCP-II used a limited set from this)~~

**Comment by brianmillsUX** [comment]
Minor copyedits only - based on limited use of [contextual] FSA iconography to date, 100% agreed.

**Comment by bignamehere** [comment]
@francisrupert  What are you thoughts on adding the Icons from PCP to FSA Style?

I think the Design System could use them.

**Comment by francisrupert** [comment]
@bignamehere,

Not quite yet. The PCP icons were a very narrow set specific to that product. 

It’s a bigger, non-trivial task. The goal is identifying a set that can cover a wide range of apps, and are all sourced from a single open source set, and easily extended by us. 

But also we need to form an opinion and recommendation if what’s appropriate. For example, my current thinking is to be very conservative on icon usage. It’s too easy to get it if hand.

**Comment by bignamehere** [comment]
@francisrupert So I propose we go with a staggered approach, and identify sets of 5 - 10 icons to make a release based on being conservative. I believe having a handful of easily identifiable icons removes a lot of cognitive dissonance, because the eye can very easily process the shape of known or standard icons.

**Comment by francisrupert** [comment]
Issue has been renamed and reframed. See [initial post for modified description](https://github.com/USDA-FSA/fsa-style/issues/49#issue-157221567).

**Comment by francisrupert** [comment]
Initial screenshot of side-by-side of key icons. 

![image](https://user-images.githubusercontent.com/1165933/109066495-c1a4ee80-76b2-11eb-9abe-a889a6b610b9.png)

**Comment by francisrupert** [comment]
**UPDATED**: screenshot comparison of _all_ key icons to test with. 

![localhost_3000_icons html (1)](https://user-images.githubusercontent.com/1165933/109322452-f67e8600-7817-11eb-8644-ea6f7c402427.png)

**Comment by francisrupert** [comment]
Created test page of **existing** icon use (possibly initially incomplete) throughout `fsa-style` to explore each candidate icon set. 

This page will additionally be extended with more speculative icon uses not currently covered by current Design System parts, and may eventually include custom implementations of FPAC Design System use elsewhere (e.g. GRA, SPAR, etc).

![localhost_3000_icon-test html](https://user-images.githubusercontent.com/1165933/109330199-0b134c00-7821-11eb-80d3-799a12f66113.png)

**Comment by francisrupert** [comment]
Current status screenshot with FontAwesome, showing...

1. Updating current components icon usage (primarily CSS-based BGs).
2. And exploratory compositions of speculative icon use.
3. Testing possible CSS Utilities for Text Colors and Background Colors (#381).

Next Step: do the same with Material.

![localhost_3000_icon-test html (1)](https://user-images.githubusercontent.com/1165933/109855903-78a6ea00-7c1e-11eb-99a6-cdb73bfd1a4b.png)

**Comment by francisrupert** [comment]
Closing. Next steps in #469.
