### ISSUE TITLE
Bugfix: Error State of Inputs with Prefix/Suffix

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/fsa-style#579]
The Error state of the Text Input component does not align properly when a Prefix or Suffix is used. (See screengrab below) 

![image](https://user-images.githubusercontent.com/2124049/185660541-a9b30315-e1b1-4239-93ab-e72397f826e1.png)

**Comment by whatnextjamie** [comment]
New modifier `--error` added for prefix/suffix label and input wrapper `.fsa-affix`

![image](https://user-images.githubusercontent.com/30541689/185971500-a5e7247a-c228-4043-89bc-56e4e31db148.png)


![Screenshot 2022-08-22 112207](https://user-images.githubusercontent.com/30541689/185970461-95daa29f-c70c-4d2f-bf8d-aa713ee9214b.png)
